// Autogenerated from Pigeon (v10.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by AppNativeApi.
NSObject<FlutterMessageCodec> *AppNativeApiGetCodec(void);

@protocol AppNativeApi
- (nullable NSString *)getHostWithError:(FlutterError *_Nullable *_Nonnull)error;
- (nullable NSString *)getBrokerIdWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void AppNativeApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<AppNativeApi> *_Nullable api);

NS_ASSUME_NONNULL_END
